### DISCUSSION TITLE
Reference Length Expression: example request

### DISCUSSION THREAD

**Discussion by rrfreimuth** [ga4gh/vrs#553] [Q&A]
Is there an example of how ReferenceLengthExpression would be used with respect to VOCA normalization? A pointer to slides when this was discussed would be helpful in the short term, but a curated example in the docs would be better long term. Thanks!

**Comment by larrybabb** [comment]
There are two test cases in the VRS test definition files which may help for now. 

A simple RLE contraction from SPDI representation
```
type: Allele
expressions:
  - syntax: spdi
    value: NC_000001.11:40819438:CTCCTCCT:CTCCT
location:
  type: SequenceLocation
  sequenceReference:
    refgetAccession: ga4gh:SQ.Ya6Rs7DHhDeg7YaOSg1EoNi3U_nQ9SvO
    residueAlphabet: na
    id: NC_000001.11
  start: 40819438
  end: 40819446
state:
  type: ReferenceLengthExpression
  length: 5
  repeatSubunitLength: 3
```

A simple RLE expansion from SPDI representation
```
type: Allele
expressions:
  - syntax: spdi
    value: NC_000001.11:40819438:CTCCTCCT:CTCCTCCTCCT
location:
  type: SequenceLocation
  sequenceReference:
    refgetAccession: ga4gh:SQ.Ya6Rs7DHhDeg7YaOSg1EoNi3U_nQ9SvO
    residueAlphabet: na
    id: NC_000001.11
  start: 40819438
  end: 40819446
state:
  type: ReferenceLengthExpression
  length: 11
  repeatSubunitLength: 3
```
