### ISSUE TITLE
Bug: Rename transformation attribute in DerivedSequenceExpression 

### ISSUE THREAD

**Issue by reece** [ga4gh/vrs#290]
Rename `transformation` to `reverse_complement`.

```
  DerivedSequenceExpression:
      ⋮
      transformation:
        type: boolean
```
