### ISSUE TITLE
Update models.yaml

### ISSUE THREAD

**Issue by korikuzma** [ga4gh/vrs#405]
The data in `models.yaml` is invalid. 

For example, `AbsoluteCopyNumber.subject` can be a `CURIE`, `ChromosomeLocation`, or `SequenceLocation` but in `models.yaml` `AbsoluteCopyNumber.subject` is a `Gene`. 

```yaml
AbsoluteCopyNumber:
  - name: ">=3 copies APOE"
    in:
      copies:
        comparator: '>='
        type: IndefiniteRange
        value: 3
      subject:
        gene_id: ncbigene:348
        type: Gene
      type: AbsoluteCopyNumber
```

This is causing tests to fail in [this](https://github.com/ga4gh/vrs-python/pull/114) VRS-Python PR.
