### ISSUE TITLE
`primaryCode` is still referenced in `CopyNumberChange`

### ISSUE THREAD

**Issue by korikuzma** [ga4gh/vrs#640]
In [GKS-Core 1.0.0](https://github.com/ga4gh/gks-core/releases/tag/1.0.0), `primaryCode` was renamed to `primaryCoding` and is now a `Coding`.

However, CopyNumberChange still references the old version in the description as seen [here](https://github.com/ga4gh/vrs/blob/2.0.0/schema/vrs/json/CopyNumberChange#L76-L78). 

I'm assuming we would represent as: 

```json
{
    "code": "0030069",
    "system": "http://www.ebi.ac.uk/efo/EFO_"
}
```

The validation tests also use this old version (https://github.com/ga4gh/vrs/blob/2.0.0/validation/models.yaml#L374-L375), but somehow the tests are still passing?

**Comment by korikuzma** [comment]
@korikuzma hold off on this until @ahwagner and @larrybabb touch base.

**Comment by larrybabb** [comment]
@korikuzma what is the `models.yaml` file used by? Why didn't our tests pick this up? The `CopyNumberChange` schema was updated to `MappableConcept` so I believe this should have been caught.  Do Cat-VRS and VA-Spec also have `models.yaml` files that need to be maintained in sync with schema updates?

**Comment by korikuzma** [comment]
VRS-Python is what usually catches any errors in the validation test suite

**Comment by korikuzma** [comment]
@ahwagner and @larrybabb  : We're going to take the VRS 1.3 model. Use the plain english description field. 

So 

```yaml
copyChange:
  type: string
  - enum:
    - complete genomic loss
    - high-level loss
    - low-level loss
    - loss 
    - regional base ploidy
    - gain
    - low-level gain
    - high-level gain
```

`description`: Describe what's in this enum.... Look at RT. Then in RTD we'll have the definitions 

- [x] We need to add to our documentation definitions for each of these terms, since we're owning this. This follows EFO concepts. 
- [x] We need to document this decision record (enum in digests / stay away from external deps)
